# Generated by Django 2.1.8 on 2019-04-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0014_classifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsettings',
            name='frontend_theme',
            field=models.CharField(blank=True, choices=[('', 'Default - Classic Bootstrap'), ('magnews', 'Magnews - Magazine & News')], default='', help_text='Change the color palette of your site with a Bootstrap theme. Powered by Bootswatch https://bootswatch.com/.', max_length=50, verbose_name='Theme variant'),
        ),
    ]
